#!/usr/bin/env bash

arg1=$1
arg2=$2
echo "Arg1 is $arg1 and arg2 is $arg2"
#
# Daemons and corresponding port(s)
#
sshd="22"
easyscp="7777 7778"
httpd="80 443"
smtp="25 587 465"
imap="143 993"
pop="110 995"
bind="53"
#
# service group and corresponding ports which can be from multiple daemons 
#
web="$httpd $easyscp"
mail="$smtp $imap $pop"
ssh="$sshd"
dns="$bind"
#
# Associative array with services as keys and their corresponding ports as value.
#
declare -A daemonports
daemonports=(
[web]="$web"
[mail]="$mail"
[ssh]="$ssh"
[dns]="$dns"
)
#
# Print the whole key->value
#
for i in ${daemonports[@]}; do echo $i;done
case $arg1 in
add)
echo "Adding rules"
#
# iptables example configuration script
#
# Flush all current rules from iptables
#
iptables -F

#Allow SSH on tcp port 22
iptables -A INPUT -p tcp --dport 22 -j ACCEPT

#
# Set default policies for INPUT, FORWARD and OUTPUT chains
#
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

#
# Set access for localhost
#
iptables -A INPUT -i lo -j ACCEPT
#
# Accept packets belonging to established and related connections
#
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
#
# Save settings
#
/sbin/service iptables save
#
#List rules
#
#iptables -L -v
;;

remove)
echo "Delete rules"


#
# Delete a rule 
#
iptables -D INPUT -p tcp --dport 7777 -j ACCEPT
;;
esac
